fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "julienrajerison5@gmail.com"
        sender_name: "julienrajerison5@gmail.com"

    registration:
            form:
                type: App\Form\Type\RegistrationFormType